# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-remote-cc

custom:
  bucket: remoto-cc

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

# The `functions` block defines what code to deploy
functions:
  crawlerRemoteJobs:
    handler: handler.crawlerRemoteJobs
    events:
      - http:
          path: crawler-remote-jobs
          method: get
          # cors: true // use only in production
